#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 22 07:57:12 2023

@author: bojack
"""


from satelite import colSatellite
from satelite import csv_from_sat
from satelite import statAnalisisData
import geopandas as gpd
import pandas as pd
import numpy as np
import gstools as gs
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import ee
import folium
import urllib.request
from io import BytesIO
from PIL import Image

ee.Initialize(
    opt_url='https://earthengine-highvolume.googleapis.com'
    )


satelliteName = 'COPERNICUS/S5P/OFFL/L3_CH4'
layer = 'CH4_column_volume_mixing_ratio_dry_air_bias_corrected'
initDate = '2018-05-31'
finalDate = '2023-08-10'

methaneSat = colSatellite(satelliteName, layer) # crea el objeto
methaneImageCollection = methaneSat.getImageCollection(initDate, finalDate) # obtiene datos para las fechas especificadas
fronterasMaritimasCol = methaneSat.getROI('fronterasMaritimasCol') # selecciona la region que ya trae el objeto
methaneImageClip = methaneSat.clipImage(methaneImageCollection, fronterasMaritimasCol) # Recorta la imagen a una región

# Plotting the image prom

viz_params = {
    'min': 1600,
    'max': 2000,
    'palette': ['black', 'blue', 'purple', 'cyan', 'green', 'yellow', 'red']
}

visImage = methaneImageClip.visualize({
    'min': 1600,
    'max': 2000,
    'palette': ['black', 'blue', 'purple', 'cyan', 'green', 'yellow', 'red']
})

print(0, '\n')

exportParams = {
  'image': methaneImageClip,
  'description': 'promedio PNG',
  'folder': 'EarthEngine',
  'fileNamePrefix': 'metano promediado',
#  'scale': 4000,
  'maxPixels': 1e13,
  'dimensions': '600x700'
}
print(1, '\n')
# Crear y enviar una tarea de exportación
task = ee.batch.Export.image.toDrive(**exportParams)
print(2, '\n')
task.start()
print(3, '\n')


